name: 'CAF landing zone deployment'
description: 'VolkerWessels biased CAF landing zone deployment'
inputs:
  action:
    description: 'CAF terraform action to run. One of (validate, init, plan, apply, show or destroy)'
    required: true
  config_dir:
    description: 'A directory in `github.workspace` containing config (*.tfvar) files.'
    required: true
  environment:
    description: 'The environment variable used in Azure tags'
    required: true
  prefix:
    description: 'The prefix variable used in Azure naming'
    required: true
  landingzone:
    description: 'the segment (launchpad, solution or add-on) of a cloud environment to deploy'
    required: true
  level:
    description: 'Deploy level'
    required: true
    default: true
  tags:
    description: 'Json string of tags to import'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV;
        echo "TFVARS_PATH=${{ inputs.config_dir }}" >> $GITHUB_ENV;
        echo "BASE_PATH=$(dirname ${{ inputs.config_dir }})" >> $GITHUB_ENV;
      shell: bash
    - name: Terraform Cache
      id: terraform-cache
      uses: actions/cache@v2
      with:
        path: |
          ${TF_PLUGIN_CACHE_DIR}
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
    - uses: VolkerWessels/conditional-composite-action@v1 # Workaround until possibility to use 'if:' option for action steps of composite actions
      with:
        if: ${{ inputs.action == 'apply' || inputs.action == 'destroy' }}
        step: |
          uses: actions/download-artifact@v2
          with:
            name: terraform-${{ inputs.landingzone }}-plan
    - name: Install landingzones
      run: make landingzones
      shell: bash
      working-directory: ${{ env.GITHUB_ACTION_PATH }}
      env:
        TF_LZ_GIT: https://github.com/VolkerWessels/caf-terraform-landingzones.git
        TF_LZ_BRANCH: 2108.0-modified
    - name: Azure login with service principal
      run: make login
      working-directory: ${{ env.GITHUB_ACTION_PATH }}
      shell: bash
    - name: Run jq command to create tags file
      run: make tags TAGS='${{ inputs.tags }}' SOLUTION='${{ inputs.landingzone }}' LEVEL='${{ inputs.level }}' CONFIG_DIR='${{ inputs.config_dir }}'
      shell: bash
    - name: Run ${{ inputs.action }}
      id: solution-deployment
      run: make ${{ inputs.action }} SOLUTION=${{ inputs.landingzone }} LEVEL=${{ inputs.level }}
      working-directory: ${{ env.GITHUB_ACTION_PATH }}
      env:
        PREFIX: ${{ inputs.prefix }}
        ENVIRONMENT: ${{ inputs.environment }}
      shell: bash
    - name: Logout service principal
      run: make logout
      working-directory: ${{ env.GITHUB_ACTION_PATH }}
      shell: bash
    - name: Store tfplan
      uses: VolkerWessels/conditional-composite-action@v1 # Workaround until possibility to use 'if:' option for action steps of composite actions
      with:
        if: ${{ inputs.action == 'plan'}}
        step: |
          uses: actions/upload-artifact@v2
          with:
            name: terraform-${{ inputs.landingzone }}-plan
            path: ${{ env.BASE_PATH }}/*.tfplan
            if-no-files-found: error

